---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ kube_resource_name }}-tls"
  namespace: {{ kube_resource_namespace }}
  labels:
    {{ kube_resource_labels | to_nice_yaml(indent=2) | indent(4) }}
type: Opaque
data:
  tls.crt: "{{ lookup('file', playbook_dir + '/files/tls.crt') | b64encode }}"
  tls.key: "{{ lookup('file', playbook_dir + '/files/tls.key') | b64encode }}"
