---
- name: Create
  hosts: docker-debug-test-runner

  tasks:
    - name: generate sufficiently random namespace name
      set_fact:
        kube_resource_namespace: "kube-resource-test-{{ (ansible_facts.date_time.iso8601_micro | hash('sha256'))[:8] }}"

    - name: create namespace
      k8s:
        definition:
          kind: Namespace
          metadata:
            name: "{{ kube_resource_namespace }}"
            labels:
              created-by: ansible-role-kube-resource-molecule
