---
- name: find namespace
  k8s_facts:
    kind: Namespace
    label_selectors:
      - created-by=ansible-role-kube-resource-molecule
  register: k8s_facts_namespace

- name: set kube_resource_namespace appropriately
  set_fact:
    kube_resource_namespace: >-
      {{ (k8s_facts_namespace.resources | json_query('[?status.phase != `Terminating`]') | first).metadata.name }}
